[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
base_sepolia = "${BASE_RPC_URL}"
base_mainnet = "${BASE_RPC_URL}"